### ISSUE TITLE
rotation

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#107]
In recent dev ( 482b9f3d4a5b23ad1a0debe3a9eb2a660e61cd06)  branch rotation throws an error:

import k3d
import numpy as np 
plt_points=k3d.points( np.random.rand(10,3).astype(np.float32),point_size=0.1)
plt_points.transform.rotation = [0.23,1,0,0]

**Comment by tgandor** [comment]
I cannot reproduce this on commit 482b9f3d, Py 3.6, windows anaconda...

I agree that the suspection of using np.float32 right in the assignment (instead of the target rotation matrix, or let's say after the final multiplication?) is founded.

Epsilon of 1e-6 is arguably quite big. What is the norm of vectors we should reasonably expect?

**Comment by marcinofulus** [comment]
seems to be an error with mkl !
