### ISSUE TITLE
Releases not tagged on Git

### ISSUE THREAD

**Issue by hadim** [K3D-tools/K3D-jupyter#126]
The last release according to PyPi is 2.4.20 where it's only 1.0.2 on https://github.com/K3D-tools/K3D-jupyter/releases.

Any reason to not add Git tags for each release?

**Comment by hadim** [comment]
ping @Gulaabihaathee

**Comment by tgandor** [comment]
This is exactly what I've noticed today ;)

The real reason is, for some time there were few published (i.e. on PyPI) releases, and then there were suddenly quite many. Having releases on the GH releases page, is low priority for us - just another metadata to maintain, but then - having tags in the Git repository is a good thing to have, and we'll address this.

**Comment by artur-trzesiok** [comment]
We will try to take care about https://github.com/K3D-tools/K3D-jupyter/releases . Thanks for that observation.
