### ISSUE TITLE
Usage in The Littlest JupyterHub

### ISSUE THREAD

**Issue by panangam** [K3D-tools/K3D-jupyter#212]
I'm new to hosting JupyterHub online in general. I followed the tutorial [here](http://tljh.jupyter.org/en/latest/install/google.html) to install JupyterHub on Google Cloud. I then installed k3d using pip. However, the widget doesn't show up in a notebook. This seems to only apply to k3d widgets, as other ipywidgets like the Buttons work fine. Any thought on what might cause this?

**Comment by tgandor** [comment]
Without going deeper into the problem, I'd try a few steps:

1 a)

`jupyter nbextension list`
And see if it says somewhere
```
      k3d/extension  enabled 
      - Validating: OK
```

If it doesn't (or if it still doesn't work anyway):
```
jupyter nbextension install --py k3d
jupyter nbextension enable --py k3d
```
(depending on how it is installed, it may require `sudo` in front or `--user` behind.

1b)

You could try to get K3D from conda instead of pip:

`conda install -c conda-forge k3d`

(it should have some hacks to facilitate K3D extension registration)

2) Restart kernels in notebooks where you test k3d

3) Hard-reload the page of the notebook (with jupyterlab, you may have to `build`, and also clean browser caches if needed)

4) Maybe, you should restart jupyter(hub) - if needed.

This is a bit of a heuristic, but it usually serves me well.

If it didn't help, we should start with - what do you get out of `jupyter nbextension list`?

**Comment by panangam** [comment]
I indeed forgot to install the nbextension 😹. Thank you for your help!
