### ISSUE TITLE
JupyterLab extension installation problem

### ISSUE THREAD

**Issue by marijanbeg** [K3D-tools/K3D-jupyter#226]
Hi, we have noticed an issue with the most recent (jupyterlab and k3d) versions regarding the k3d extension installation for JupyterLab. The commands:

```
pip install k3d jupyterlab
jupyter labextension install @jupyter-widgets/jupyterlab-manager k3d
```

run successfully, but k3d does not display plots. Instead, `Error displaying widget: model not found` is shown (and some of our users report `Loading widget...`).

Is there a fix to this issue? Many thanks!

**Comment by efirdc** [comment]
Looks like a great extension, but I am encountering the same issue. Here is the console output I get:

![image](https://user-images.githubusercontent.com/5416313/83958657-8ff0ac80-a831-11ea-849f-30a50c8a1c33.png)

**Comment by daoprinciple** [comment]
Hi, I also faced the similar problem for showing the figure in jupyterlab `Error displaying widget: model not found` or `Loading widget`. However, it is normal for using the jupyter notebook.
The installation method is the same as @marijanbeg.

Package version
python 3.6.8
jupyter 1.0.0
jupyterlab 2.1.3
K3D 2.8.2
ipywidgets 7.5.1

**Comment by sunilkpai** [comment]
I am also getting the same issue in jupyterlab but it works for me in jupyter notebook!

It would be great to make this work in jupyterlab for my workflow.

**Comment by skuschel** [comment]
I am getting the exact same error `Module k3d, semver range 2.9.0 is not registered as a widget module` under Arch Linux.
python 3.8.6, output of `jupyter --version`:
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : not installed
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.8
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3
```
`jupyter lab --version` is `2.2.8` 

Also I noticed, that there is k3d v2.9.0 in pip, but doesnt exist on github. Latest version tag on github is k3d v2.8.2...

**Comment by vctmohan** [comment]
> 
> If someone can give me a hint where to start, I am happy to help debugging/fixing the problem!

I recently came across k3d and tried to use it for a demonstration. I had the same issue, had to spend some time to work around this issue. Here are my observations:

* This issue is primarily due to the Jupyter widget incompatibilities between package requirements of JupyterLab and K3D. This can be observed if you take a look at the packages installed in npm staging area, and look at the requirements for JupyterLab and K3D.
* K3D doesn't seem to support Jupyterlab 2.0. You have two ways to use K3D with JupyterLab as of now.
* Install JupyterLab 1.28 using pip install jupyterlab==1.2.8 and install K3D.
* Alternately, you can update the package.json and install K3D from source as described in https://github.com/K3D-tools/K3D-jupyter#source. Here is the update I have been using successfully for a while, https://github.com/vctmohan/K3D-jupyter/commit/8d6d856439a8610a4e482a44010ed47f09b4a2f8. Patch the js/packages.json file before you run the pip install, and you should get you a working K3D installation with JupyterLab 2.0.

**Comment by artur-trzesiok** [comment]
Please check https://github.com/K3D-tools/K3D-jupyter/pull/249/commits/998bccb9b4f767f7c8c901bd74267f1c646fcb27 - release 2.9.1
