### ISSUE TITLE
Color map and color legend in 'points' type plot

### ISSUE THREAD

**Issue by zbouslikhin** [K3D-tools/K3D-jupyter#227]
Hi,
After spending quite some time without any success trying to add a color legend to a points type plot, I was wondering if it is actually possible?

Cheers,
Zaid

**Comment by tgandor** [comment]
Hi Zaid,

There are some limitations about the color legend. E.g. there can only be one per plot.
Second, the Color Map is tied to a single object.
Third, this object must itself have a color map, so it must be one of: Line, Mesh, Surface, Texture, Volume, ...

Points is not on that list - it has just discrete colors as packed RGB ints, and no float `attribute`.
How do you pass colors to your points? Do you happen to use `k3d.helpers.map_colors`?

A workaround for now - add an "invisible" Volume or (better yet) Mesh or Line to your plot, which has the right color map and attribute range, and you'll get the Color Map.

**Comment by zbouslikhin** [comment]
Indeed. That does the job. Thanks.
Is it planned to implement adding a color map to` Points` type object?
In the same occasion, as I'm not sure whether I'm about to describe is a normal behavior or not, I didn't want to open an issue about it.
While updating the Color Map of the "invisible" line by using `line.color_map = `, it doesn't automatically update the color legend until done manually by disabling/enabling it through the GUI found in the plot.

**Comment by tgandor** [comment]
1. Right now I don't know about any plans about it. We have talked a bit about more customization for the color bar, but there is a combinatorical number of feature combinations needed to satisfy everybody... 

It may be better to draw a colorbar as a texture, or maybe have some Drawable class which works like a Text2D or something. As I said, there are no specific plans yet.

2. Actually, I have had something similar. It wasn't about the bar, but about the ticks. Because I was tinkering with the `plot` parameters, and not the object which owned the color map, I thought this could be ok. I need to ask my team mates how to trigger the color bar refresh. Thanks for pointing to this. Maybe you could close this issue and open another for the refresh (with a minimal code to reproduce)?

**Comment by artur-trzesiok** [comment]
I like idea of adding k3d.points(attribute=...., color_map=...., color_range=....., opacity_function=....). That will make our API more consists.

**Comment by artur-trzesiok** [comment]
![image](https://user-images.githubusercontent.com/5256837/118248773-a7bfbe80-b4df-11eb-892f-e39b125dfb7b.png)

**Comment by zbouslikhin** [comment]
Hi @artur-trzesiok,

Sure, I'll try this as soon as possible and get back to you with some feedback about it!

**Comment by zbouslikhin** [comment]
![image](https://user-images.githubusercontent.com/47977073/119356910-3e8e3700-bca7-11eb-985f-13104c862bbd.png)

@artur-trzesiok Awesome. Works like a charm!
