### ISSUE TITLE
Render non-continuous line / mesh vectors?

### ISSUE THREAD

**Issue by mironvanderkolk** [K3D-tools/K3D-jupyter#241]
I'm looking for a way to visualize a group of cylinders/line segments in k3d. So far I have tried using `k3d.vectors` but that only renders flat lines. I tried using `k3d.line` but that forces all the segments to be connected. Using a separate `k3d.line` object for every cylinder impacts performance a lot if I try to render more than ~100 objects.

Is there any way other way to draw a large amount of objects? Similar to the pointcloud perhaps?

**Comment by artur-trzesiok** [comment]
I see two options

# Proper way
Please generate whole gemetry as one big mesh and send it to k3d via k3d.mesh with vertices and indices. You can use for example vtk library

# Hack way
import k3d
import numpy as np

N = 1000

```
v = np.cumsum(np.random.randn(N,3).astype(np.float32), axis=0)
v[3::4, :] = np.nan
v[1::4, :] = v[2::4, :] - (v[2::4, :] - v[0::4, :]) * 0.0001

plot = k3d.plot()
plot += k3d.line(v, shader='mesh', width=0.1, radial_segments=16)
plot.display()
```

Hack use internal js implementation that make hole in segment if there is a nan value. But we still need at least 3 points per tube because normaly k3d calculate joints strategies base on three points in a row.

![image](https://user-images.githubusercontent.com/5256837/93603823-d1fac400-f9c4-11ea-9612-0bcc08049c08.png)

**Comment by mironvanderkolk** [comment]
Thanks for the response, I'll try both options
