### ISSUE TITLE
Static html examples gallery

### ISSUE THREAD

**Issue by artur-trzesiok** [K3D-tools/K3D-jupyter#25]

**Comment by tgandor** [comment]
This issue is still in progress. Some refreshments were made along the way in other tasks, but this is not what I want to achieve. And that would be:

I. Example composition and layout

1. More complete "tutorial" examples (with names starting with a number, like 01_getting_started.ipynb), which should include (some are :
  - 03_camera_position
  - 04_plot_options (or 2 separate: 04_grid_adjustment, 05_camera_adjustment), um... maybe 04_plot_auto_adjustment
  - 05_taking_screenshots
  - 06_editing_voxels (this is part of the UI, so "tutorial", but then see point 2. below)
  - 07_model_matrices_and_transforms
  - 08_colors_and_color_maps
  - 09_animation
  - 10_interaction_with_widgets
  - ? 11_data_formats (STL, VTK)
  - (...)
  - ? 99_extending_k3d - maybe an example how to create a Drawable for TorusKnot (only JS primitive without Python counterpart). Our user base may not be into implementing new object loaders in the ThreeJS provider...

2. The per-Drawable examples - with names like functions from `k3d`: vectors.ipynb etc. There can be multiple examples for a Drawable - like now vector_field_2d and vector_field_3d. And voxels / voxels_edit.
Well, this example is a bit special, because it touches a unique feature - editing in the plot.
Maybe these examples should be numbered, maybe prefixed with a same number (and then sorted alphabetically), maybe not. AKA: Drawable examples, Drawable API reference examples.

3. Demo-examples. These are comprehensive examples, which show off more difficult tasks, or multiple features at once, or are real life demos with mathematical or physical insight - double pendulum, point cloud from 3D scanner, historical successes of k3d.
These examples, if numbered, should come near the end (high common number prefix), maybe in a subfolder (I don't like this), or prefixed with "demo_" or sth like that.

4. Unit tests and less presentable stuff - um, these I would put into a subfolder. Don't have a name yet. Needs not be to derogatory, like 'deprecated/", but maybe "test/" and "misc/" - so only the nerds will check them out.

II. Extra improvements

1. Additionaly to the points above - the examples should be supplied with a static screenshot in the attached Markdown text, so that they can be viewed on github, or just in the user's jupyter even without executing them (especially the "Tutorial" part - as now with "expected result", but "demos"  and "API reference" may benefit from screenshots as well)

2. Linking to the examples in Drawables/k3d module functions docstrings. (If possible to render a link in jupyter's docstring window)
