### ISSUE TITLE
get_snapshot result with wrong zooming or camera view

### ISSUE THREAD

**Issue by wnhfyang** [K3D-tools/K3D-jupyter#251]
When using plot.get_snapshot and open the saved html file, the result looks strange: it is zoomed to show a very large plot. An example is demonstrated as the following. Even though I can use a mouse the zoom out, it is not very convenience. How to solve this problem? (I have tried to use fetch_snapshot and then f.write(plot.snapshot), but the result is an empty html file. I can save the correct html file by using the command within the plot, but it costs my computer to freeze for about 1 min, and it consumes a huge amount of memory) Any help is appreciated. Thanks.

import k3d
import numpy as np

x = np.random.randn(1000,3).astype(np.float32)
point_size = 0.2

plot = k3d.plot(name='points')
plt_points = k3d.points(positions=x, point_size=0.2)
plot += plt_points
plt_points.shader='3d'
plot.display()

f = (np.sum(x**3-.1*x**2,axis=1))
colormap = k3d.colormaps.basic_color_maps.WarmCool
colors = k3d.helpers.map_colors(f,colormap,[-2,.1])
colors = colors.astype(np.uint32)

plt_points.colors = colors

test = plot.get_snapshot()
with open('./points.html','w') as fp:
    fp.write(test)

**Comment by marcinofulus** [comment]
It is caused by `plot.display()` which takes more time then this code execution. Thus camera does not auto-zoom before shapshot. 
The solution is split cells after `plot.display()` or explicitely wait e.g. 1s after display().

You might also look at `screenshot_generator.ipynb` example which uses mechanism which circumvents asynchronous execution of screenshots, which might be necessary for e.g. animations.

**Comment by artur-trzesiok** [comment]
It's worth to implement at backend level plot.camera_reset() . Probably:

` plot.camera_reset(backend=True)`

That will be usefull.

**Comment by artur-trzesiok** [comment]
`plot.camera = plot.get_auto_camera(yaw=0, pitch=90, factor=1.5)`

Please try in new release
