### ISSUE TITLE
Wrong Python version

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#275]
If I click on the menu -> Info -> `Python version` is equal to  `Js version`, 2.9.4 in my case. I believe this is a minor bug.

**Comment by marcinofulus** [comment]
it should be equal, it happens to be unequal if nbextension is from old version.

**Comment by tgandor** [comment]
Hi, @Davide-sd!

These two numbers are version numbers of K3D, not versions of  the interpreters. (So it shouldn't show your Python interpreter version).

When you install K3D for the first time, these version always match, which means everything is OK.

Then, suppose we fix a bug in 2.9.5, or enhance some functionality. You'll do `pip install -U K3D`, restart your notebook kernel, and create a plot. But - the functionality seems not to work. It's there in the Python API, but has no effect on the plot. It's because your browser has cached the JS part. This is when you'll see "Python version: 2.9.5" and "JS version: 2.9.4".

When using Notebook, you can check the extensions `jupyter nbextension list`, maybe re-install the extension (see README) and hard-refresh the notebook page (or clean cache). I'm not sure about JupyterLab, but you probably need to rebuild it, and also reload the page.

@artur-trzesiok - maybe "frontend version" and "backend version" would be better names?

And for the Python version one should use: `import sys; print(sys.version); print(sys.version_info)` ;)

**Comment by Davide-sd** [comment]
Thanks @tgandor for this excellent explanation. I feel like this is worth to be included somewhere in [the documentation](https://k3d-jupyter.org/), maybe a new section "ugrade".

**Comment by Davide-sd** [comment]
Hello @artur-trzesiok , I installed the new version and I noticed that: 

```
JS version: 2.9.4
Python version: 2.9.5
```

I tried everything I could think of:
* I cleared the browser cache.
* I deleted my environment and reinstalled all packages.
* I deactivated K3D Jupyter extension, restarted the server and reactivated it.
* I fresh-reloaded the jupyter notebook page.

And nothing, it still loads JS version 2.9.4. What can I try?

**Comment by Davide-sd** [comment]
Ok, I think I understood what went wrong. I had K3D 2.9.5 installed on my development-environment and K3D 2.9.4 installed on my system. I think somehow the development-environment was looking at the files of the system. After uninstalling both version and reinstalling the latest on my development environment, everything works fine now.
