### ISSUE TITLE
link ipywidgets to `save screenshot` and `fullscreen` methods on client side

### ISSUE THREAD

**Issue by esalehim** [K3D-tools/K3D-jupyter#289]
Is it possible to register a ipywidget click event to perform save screenshot or change full screen mode, preferably using `jlink`?
I know about the menu panel but I need to link to a Button widget in the notebook

**Comment by artur-trzesiok** [comment]
I inspected this topic a little bit. 
https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

"Note: This method must be called while responding to a user interaction or a device orientation change; otherwise it will fail."

so triggering a fullscreen from python via plot.fullscreen = True cannot be done. So that will be a first time in k3d when we will have exposed variables for js but not python. The same topic is related with downloading a file (screenshot) without user interaction. This is a security issue (lets imagine that some webpages will run 1000 downloading of files in loop or run "silent" fullscreen with "simulation" of your desktop.

So I'm afraid that this will be too hard
