### ISSUE TITLE
Mesh Callbacks - Show the attribute value

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#297]
I'm looking at this tutorial: [mesh callbacks](https://k3d-jupyter.org/basic_functionality/Mesh_callback.html), in which the position of the mouse over the mesh is shown.

I'd like to also show the local value of the attribute. Sadly, `"attribute"` is not on the keys of the dictionary `p` in the callback. Is there some hidden way that I can add it?

**Comment by artur-trzesiok** [comment]
Because that depends how do you want to calculate it:
![image](https://user-images.githubusercontent.com/5256837/126231210-8e3888a6-1237-4e0e-857b-9a194413f4f9.png)

```
def foo(params):
    global debug_info, obj
    
    indices = params['face']    
    p = np.array(params['position'])
    vertices = obj.vertices[indices]
    attributes = obj.attribute[indices]
    
    f1 = vertices[0] - p
    f2 = vertices[1] - p
    f3 = vertices[2] - p
    
    a = np.linalg.norm(np.cross(vertices[0] - vertices[1], vertices[0] - vertices[2]))
    
    a1 = np.linalg.norm(np.cross(f2, f3)) / a
    a2 = np.linalg.norm(np.cross(f3, f1)) / a
    a3 = np.linalg.norm(np.cross(f1, f2)) / a
  
    value = np.sum(np.array([a1, a2, a3]) * attributes)
    debug_info.value = 'Python: ' + str(value) + ' Js:' + str(params['uv']['x'] * obj.color_range[1])

obj.click_callback = foo
obj.hover_callback = foo
```

Since 26 V 2021 callback returns z uv params. Mesh with attribute code colormap as 1d texture so in uv in fact is located a interpolated attribute: https://github.com/K3D-tools/K3D-jupyter/blame/main/js/src/k3d.js#L404

**Comment by Davide-sd** [comment]
Thanks @artur-trzesiok , I'll give it a try and let you know!

**Comment by artur-trzesiok** [comment]
@Davide-sd can we close this issue?

**Comment by Davide-sd** [comment]
Sure! :)
