### ISSUE TITLE
Timeseries does not work for vectors?

### ISSUE THREAD

**Issue by tfunatomi** [K3D-tools/K3D-jupyter#310]
Hello,
k3d is so helpful. 
I deeply appreciate the developers of this project.

I tried to make an animation using k3d.vectors and found an issue probably.

I understand from the below that Timeseries must be set to model_matrix in k3d.vectors
https://github.com/K3D-tools/K3D-jupyter/blob/102bdbfde6058285439b589caef6a2f936e90986/k3d/factory.py#L955
and it seems correct in the below.
https://github.com/K3D-tools/K3D-jupyter/blob/102bdbfde6058285439b589caef6a2f936e90986/k3d/objects.py#L1073

However, it does not show animation in my environment.
The same approach worked for points, so I believe it is correct.
```
import k3d
import numpy as np

vertex = np.random.rand(4,3)
transforms = [np.array([
    np.cos(theta),-np.sin(theta),0,0, 
    np.sin(theta),np.cos(theta),0,0, 
    0,0,1,-theta, 0,0,0,1
]) for theta in np.linspace(0,1,100)]

plot = k3d.plot()

vectors = k3d.vectors(vertex[:2],vertex[2:]-vertex[:2])
vectors.model_matrix={'%.f'%(t/10):transforms[t] for t in range(len(transforms))}
plot += vectors

points = k3d.points(vertex,point_size=0.05) 
points.model_matrix={'%.f'%(t/10):transforms[t] for t in range(len(transforms))}
plot += points

plot.display()
plot.start_auto_play()
```

I appreciate it if you could help.

Best regards,

**Comment by artur-trzesiok** [comment]
@tfunatomi Thanks for a kind words. I see that description : "kwargs: `dict`. Dictionary arguments to configure transform and model_matrix." is misleading. I will refine it.

In K3D we have two groups of primitives.

Defined as **absolute positions**:
- k3d.line
- k3d.points
- k3d.vectors
- k3d.text
- k3d.text2d
- k3d.texture_text
- k3d.label

Defined in **object space**  and positioned in global space via modelMatrix

- k3d.marching_cubes (by default in cube [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5])
- k3d.mesh
- k3d.vtk_poly_data
- k3d.stl
- k3dsurface (by default in box [-0.5, 0.5, -0.5, 0.5] with heights from data)
- k3d.texture (by default in plane [-0.5, 0.5, -0.5, 0.5])
- k3d.vector_field (by default in cube [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5])
- k3d.voxels (by default in cube [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5])
- k3d.voxels_group (by default in cube [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5])
- k3d.sparse_voxels (by default in cube [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5])
- k3d.volume (by default in cube [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5])
- k3d.mip (by default in cube [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5])

So k3d.vectors dosen't support model_matrix nad thats why it isn't working. Instead of animating a model_matrix you can animatate _origins_ and _vectors_ attribute.

@marcinofulus @tgandor this should be a part of official documentation or we should add support to model_matrix to all kind of objects.

**Comment by artur-trzesiok** [comment]
I dive into topic. What I discovered: 
- k3d.line 
- k3d.points

already have support to additional transformation via model_matrix. So I added that also to:

- k3d.label
- k3d.text
- k3d.texture_text
- k3d.vectors

So right now **all k3d primitives has support to model_matrix.**

so @tfunatomi thanks for that ovservation! Please look forward to next release of k3d

**Comment by tfunatomi** [comment]
@artur-trzesiok 
I appreciate your work!
