### ISSUE TITLE
VectorsFields is strange grammar

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#32]
Proper plural forms: one "vector field", several "vector fields".

**Comment by martinal** [comment]
Same with "scalars_field" in the marching cubes demo, correct name would be "scalar_field".

**Comment by tgandor** [comment]
Acknowledged.

I can only add to this list several other cases that we need to rename en masse:
points_cloud -> point_cloud
points_positions -> point_positions
voxels_edit.ipynb -> edit_voxels.ipynb ("edit" as verb) or voxel_edit.ipynb ("edit" as noun)
points_colors -> point_colors
labels_size -> label_size
... - if I find anything else, it will also be fixed.

This is an unfortunate interference from Polish grammar - color map is "map of colors", and we say literally "colors' map" (https://en.wikipedia.org/wiki/English_possessive).

**Comment by martinal** [comment]
I think this is fixed now?

**Comment by tgandor** [comment]
When doing some API changes for the upcoming release, this object was further renamed to "VectorField" - yes, the function can draw 2 kinds of vector *fields* (2D and 3D), but - for each call there is just one VF.

These changes are still on `devel` and wait to be released, but I think this issue is done.
