### ISSUE TITLE
Coordinate axes should show the +- extents

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#33]
Currently the coordinate axes only show where 0 is for x,y,z, but not what the max/min values of x,y,z are. This is crucial information. Is it possible to show it today? I think it should be default behaviour.

**Comment by marcinofulus** [comment]
It shows automatic ticks with labels if axes range is large enough. It still needs improvements and possibly some manual controll.

**Comment by artur-trzesiok** [comment]
To be honest bounding box not always need to contain (0,0,0). Grids should automaticly adopt to scene like here:

![k3d-1496171202541](https://cloud.githubusercontent.com/assets/5256837/26600325/f680eec2-457b-11e7-9128-b8ab346b1834.png)

**Comment by artur-trzesiok** [comment]
I changed to show by default (-2,2) per axis

**Comment by martinal** [comment]
Just tried the `vector.ipynb` example and it still doesn't show the outermost extents, same thing in your figure above. What I mean is that when the grid shows x in [-30, 30] the numbers -30 and 30 should be included. You can of course consider this an opinion. Is it possible to turn that on manually at least?

**Comment by artur-trzesiok** [comment]
Because every axis is calibrate separatly there is a option that on corner point will have two different value. Like on screenshot above in corner nearest to us on x ais should be 30 and on y axis should be 20. This is quite difficult to render this two values in the same place without overlapping and without confusing .

@marcinofulus : what do you think about it?

**Comment by martinal** [comment]
I guess this is not crucial and I see it's a bit tricky to to well. Closing.
