### ISSUE TITLE
Use instancing to render glyphs more efficiently

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#40]
I see in `vectors.js` that you do:
```
            useHead ? new THREE.Geometry().copy(singleConeGeometry) : null,
```
i.e. you make a copy of the cone head for each glyph.

A possible optimization is to use instanced rendering, avoiding duplication of the glyph model.

https://threejs.org/docs/#api/core/InstancedBufferGeometry

Consider this if deciding to pursue an improved glyph model as I suggested in
https://github.com/K3D-tools/K3D-jupyter/issues/38

**Comment by artur-trzesiok** [comment]
Instancing geometry will be not necessary faster. For animated vectors probably yes but for static data one buffered geometry is pretty fast. Look at https://github.com/K3D-tools/K3D-jupyter/blob/devel/js/src/providers/threejs/helpers/Fn.js#L136 - i merge all heads into one buffer

all heads have merged vertex data so whole geometry are placed on GPU memory. Every head contain only 5 triangles. Because of that i think the benefits from this feature will be not that important unless we don't try to render 1kk vectors but for that case we had useHead param.

@marcinofulus what do you think?

**Comment by martinal** [comment]
I guess there's no functionality improvement in this, pure optimization, so if it's fast enough then no point.
