### ISSUE TITLE
Implementing click_callback Functionality(Lack of clarity/focused example script)

### ISSUE THREAD

**Issue by DhruvaRajwade** [K3D-tools/K3D-jupyter#408]
* K3D version: 2.15.2(installed via conda-forge)
* Python version:Python 3.9.12
* Operating System: Arch Linux, Kernel: 6.1.1-arch1-1

### Description

I was studying the mesh_callback example, linked [here](https://github.com/K3D-tools/K3D-jupyter/blob/main/examples/mesh_callback.ipynb). I wanted to implement the click functionality to display metadata about a node when a graph is created, but could not get the on_click functionality to work.

Here is an example graph(Z=0), and what I was trying to do is get some metadata using the on_click callback when a point is clicked.
![K3D_2D_Points](https://user-images.githubusercontent.com/75108925/210072102-95b99b0d-1ea9-4b16-85c9-ba93e96e3462.png)

### What I Did
I had a list of points(x,y,0). I converted them into a numpy array. I also had an array with areas for each set of Co-ordinates.
Here is the code I tried.
```
plot = k3d.plot()
object = k3d.points(xyz_coords, point_size=2)
plot += object
plot.mode = 'callback'
obj = plot.objects[0]
def display_area(obj):
  for i in range(31):
    if obj.positions == obj.positions[i]:
      point_id = i
    else:
        point_id=-1
  if point_id==-1:
    pass
  else:        
    area = areas[point_id]
    print(f"The area of the selected point is {area}")
obj.click_callback = display_area
plot.display()
```
I understand I must be doing something wrong(my display_area function seems very dodgy). What should I do to get the areas when I click on a point?
(I don't need the points to be exactly the size as their areas denote, they are merely for a graph representation with areas as features)

**Comment by artur-trzesiok** [comment]
Hi!

Your example is not working because k3d.points is not a DrawableWithCallback object

https://github.com/K3D-tools/K3D-jupyter/blob/5052d607bb0d05177abdf5b0e3f5d97a2920af53/k3d/objects.py#L181)

So K3D at this moment simply dosen't support callbacks for 

- k3d.points, 
- k3d.line, 
- k3d.lines, 
- k3d.stl, 
- k3d.text, 
- k3d.text2d, 
- k3d.label, 
- k3d.texture_text, 
- k3d.vector_field, 
- k3d.vectors, 
- k3d.volume, 
- k3d.mip, 

callbacks are available for:

- k3d.marching_cubes
- k3d.mesh
- k3d.surface
- k3d.texture
- k3d.voxels
- k3d.sparse_voxels
- k3d.voxels_group

It is visible in code execution:
![image](https://user-images.githubusercontent.com/5256837/210103003-c43fe2a3-a8e8-42a6-ae80-239288f4527e.png)

I will try to add that to documentation too.

**Comment by DhruvaRajwade** [comment]
Thank you for the prompt reply! One last query, will callback support be added to the k3d.points object in the near future?

**Comment by artur-trzesiok** [comment]
That will be dedicaded mechanism just for points (goal is to calculate ray-sphere intersection rather than ray-mesh). But many people use k3d.points with milions of points so even here I should have some octree... It is not stright forward

**Comment by artur-trzesiok** [comment]
Good news! BVH that we use has support for points - https://gkjohnson.github.io/three-mesh-bvh/example/bundle/pointCloudIntersection.html 

I feel we can do that in k3d soon but I don't want to make a promises :)

**Comment by artur-trzesiok** [comment]
btw my benchmark data to picking - 24m of points (credits: https://sketchfab.com/3d-models/recovering-oak-point-cloud-version-f6dd3f2b081b483bb3f40b6b931016fd )

**Comment by artur-trzesiok** [comment]
Click callback functions #409

Callback "on hover" to python. Green boxes shows BVH Tree [for debug purpose only] on 8 mln of points:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/5256837/222443420-edb05ca8-7142-4219-bcd5-d89c03d1b5ed.gif)
