### ISSUE TITLE
better check/warning on data inconsistency

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#59]
`import  k3d 
import numpy as np
plot = k3d.plot()
plot += k3d.points(np.array([[0,0,0], [0,0,2.5]]), colors = [0xff0000])
plot.display()

`

Produces an empty plot. The user mistake is that one color is given for 2 points. It should checked and error displayed.

**Comment by tgandor** [comment]
Thank you for pointing this out.

I see some further issues in this area:
1) `color` and `point_colors` (named `colors` in the wrapper function) - redundant, and not clear from API which takes precedence - are both allowed?
2) This would be further complicated if color maps for points are implemented.

Proposed solutions:
A) just validate if  len(point_colors) in [0, len(positions)], else raise ValueError
B) Refactor this, and remove redundancy: colors=[_default_color].
How to solve the size mismatch?
B1) validate if len(positions) == len(colors) else raise
B2) cycle the values of colors for the points
-> validate if len(colors) != 0 else raise

The B2 variant probably requires some changes to JS part.

What do you think about this?

**Comment by tgandor** [comment]
After talking to Artur I am dropping the idea of "automatic cycling" of `colors` array on the JS side. (this can be done by the user consciously if needed)

I may still do something about `points` argument name vs. `Points` attribute name mismatch: in my view this should be identical, i.e. "colors", "positions" etc. (the user knows they're point positions).

**Comment by tgandor** [comment]
I went for a different solution - because the traitlets of Points can't be set atomically (I mean setting both colors and positions in a single "transaction"), we need to be able to do it (and not raise a traitlet validation error).

A (possibly) common scenario is: adding more points (see: point_cloud_scanner.ipynb example). Maybe we should forbid this, and rewrite the example to add each chunk as a separate Points object. But even then - validation in the other direction cannot be strict - we need to set positions first, and then colors (the __init__ does the same, it doesn't bypass validation).

So - I added a fallback to default color (the points weren't displayed because of an error in THREE.js - index out of range in buffer). Now there is no error, and points are visible. When the color arrive, they will be redrawn correctly.

I propose to leave it like this.
