### ISSUE TITLE
camera distance

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#67]
If one makes a plot with small  bbox and then:

 sets 
plot.grid_auto_fit=False
plot.camera_auto_fit=False
 
then 
1. the direct voxel update (e.g p.volxels=b) bring back wrong  dynamic calculations related to scene size.

2. detaching and attaching display producess -1,1 bbox again

example

import k3d 
import numpy as np 
import time
v = np.random.randint(0,10,size=(5,5,5))

plot = k3d.plot()

bbox = np.tile([0,1e-3],3)
plt_vox = k3d.voxels(v,bounds=bbox)

plot += plt_vox

plot.display()
time.sleep(1)

plot.grid_auto_fit=False
plot.camera_auto_fit=False
time.sleep(1)
plt_vox.voxels = np.random.randint(0,10,size=(5,5,5))

**Comment by tgandor** [comment]
I just tested it and something seems wrong (2.4.18).
I have split the example into cells instead of doing time.sleep(1), and ran the cells separately.
After turning off both, I get a white background, with axes' labels above.
Setting it back to true (both) brings the "Rubik cube" back, with axis-walls and everything.
