### ISSUE TITLE
rotation seems not to work properly

### ISSUE THREAD

**Issue by marcinofulus** [K3D-tools/K3D-jupyter#94]
In example texture.ipynb 
adding:

import math
texture.transform.rotation = [math.cos(math.radians(30)/2),1,0,0]

does not work, 

however it works: 

texture.transform.rotation = [math.cos(math.radians(30)/2),0,1,0]

**Comment by tgandor** [comment]
I found one problem, which could have caused many trouble, like the one mentioned above
(a formula mistake).

Also note, that we changed the convention - now it's not a quaternion / pseudo quaternion with non-unit vector part, but the first element is angle in radians, so the above code would become:

import math
texture.transform.rotation = [math.radians(30), 1, 0, 0]

I'll add a unit test for a few simple rotations and see if this issue is resolved.

**Comment by marcinofulus** [comment]
still does not work:

import k3d
import math

texture = k3d.texture(open('assets/texture.png', 'br').read(), 'png', 
                      rotation=[math.radians(25.1),1,0,1])
plot = k3d.plot()
plot += texture
print(texture.model_matrix)
texture.transform.rotation = [math.radians(65),0,1,0]
print(texture.model_matrix)

plot.display()

**Comment by tgandor** [comment]
OK, there was a certain "new_matrix" introduced, which was causing the problem.
Right now the rotation (or any other transformation) is again effective.
Now we just need to add some (unit) tests for our mental comfort.
